### ISSUE TITLE
Moving window can become frequently unaligned

### ISSUE THREAD

**Issue by nsjames** [edenia/ultra-faucet#7]
There is a clear window within the smart contract of how many tokens can be given within the interval, however in this implementation the window movement isn’t clearly defined. It is based on when the next claim starts instead of the end of the previous window, leaving gaps in the timeline. 

The optimal solution would be that each window starts at exactly the moment the previous window ends, so that the total amount of tokens given over the broader timeline is expressed deterministically. For instance; 24 hours and 1000 tokens should equal no more and **no less** than 365,000 tokens over 1 year. 

https://github.com/edenia/ultra-faucet/blob/main/faucet/src/faucet.cpp#L45

**Comment by leisterfrancisco** [comment]
Thank you very much @nsjames.

What would happen if a faucet transfer is less than the maximum token per window time after the first window ends? Will it stack in the next transfer window?

**Comment by nsjames** [comment]
Ideally it would work like so:

----------------------------------------------------------------------
1000 available | 1000 available | 1000 available | 1000 available | 
      1 hour       |        1 hour       |        1 hour      |       1 hour        |
----------------------------------------------------------------------

So every hour 1000 UOS would be available for claiming.

**Comment by nsjames** [comment]
Thanks, looking into this now :)
