### ISSUE TITLE
Tokens might not be dispensed as expected based on the parameters. 

### ISSUE THREAD

**Issue by nsjames** [edenia/ultra-faucet#8]
If `transferred_tokens` is less than `max_tokens_per_interval` it will always try to mint `TOKENS_PER_REQUEST`. So if `transferred_tokens` is 10, `max_tokens_per_interval` is 11 and `TOKENS_PER_REQUEST` is 10 then `transferred_tokens` will become 20 and 10 tokens will be transferred.

https://github.com/edenia/ultra-faucet/blob/main/faucet/src/faucet.cpp#L50

**Comment by leisterfrancisco** [comment]
@nsjames what a nice catch, thank you very much.

Here is the [PR](https://github.com/edenia/ultra-faucet/pull/9) that solves the issue you comment on, take a look and let us know what you think.

**Comment by nsjames** [comment]
Looks good, thanks :)
